### ISSUE TITLE
Enhancement: Add labels in the PDF output

### ISSUE THREAD

**Issue by MariannaPaszkowska** [behdad/halfkern#12]
I think it would be good to have the tool explicitly label the images in the output PDF to identify:
'No Kerning Applied'
'Suggested Kerning'
'Original Font Kerning'
These labels will make the PDF much more informative and accessible, especially when shared with a design-focused audience who is not familiar with the tool and needs to quickly understand the differences between the kerning options presented in the PDF.

**Comment by behdad** [comment]
Is it good enough to add a legend page at the beginning?

**Comment by MariannaPaszkowska** [comment]
I don't think this would be sufficient. Someone might want to share just a page.

**Comment by behdad** [comment]
Okay. I'll work on it.
